### ISSUE TITLE
move make.m up a directory

### ISSUE THREAD

**Issue by ahbarnett** [stefanengblom/stenglib#2]
Dear Stefan,
Just to let you know I had to move make.m up a directory from Fast/source to Fast/  since it expects to look into pwd / source. Then it built fine. I'm on ubuntu 16.04 linux, Matlab R2017a.

But on 4-core i7 it doesn't beat the native matlab by much (here openmp=true):

% test speed of forming sparse mats, including stenglib. Barnett 10/10/18
addpath ~/matlab/stenglib/Fast
clear
n = 1e5;
nnz = 3e7;
i=randi(n,nnz,1);
j=randi(n,nnz,1);
a = rand(nnz,1);
tic; A = sparse(i,j,a,n,n); toc        % single thread
tic; A = fsparse(i,j,a,[n,n,nnz]); toc   % is multi thread
tic; A = fsparse(i,j,a,[n,n,nnz],'nosort'); toc    % seems single thread
tic; [i,x]=sort(i); j=j(x);a=a(x); A = fsparse(i,j,a,[n,n,nnz]); toc % slowest
tic; A = fsparse(i,j,a,[n,n,nnz]); toc % after sort, fast

Elapsed time is 4.991984 seconds.
Elapsed time is 3.538113 seconds.
Elapsed time is 3.828368 seconds.
Elapsed time is 5.219050 seconds.
Elapsed time is 1.020627 seconds.

With openmp off the 'nosort' case is still 4.4 s, ie faster than matlab.

I imagine this is because it's memory-bandwidth limited. I'll try xeon next.   Anyway, thanks for writing it!
Alex

**Comment by ahbarnett** [comment]
Sorry, I now see that startup.m adds source/ as part of the path, so make.m can be run from Fast/
I guess this makes sense. It might be worth adding to instructions to run startup.m first, and that compile options for Fast/ can only be set by cd to Fast/ then run startup then run make.

Timings on 12-core xeon are great:! For above code:
Elapsed time is 4.649347 seconds.
Elapsed time is 0.804290 seconds.
Elapsed time is 3.528820 seconds.
Elapsed time is 3.325252 seconds.
Elapsed time is 0.349999 seconds.

Thanks for writing, Alex

**Comment by shrike77101** [comment]
Hi Alex, I'm new to matlab and struggling to run make.m at all. I'm using Matlab 2019b and I notice that you use 2017a. Very surface level question: is there anything in make.m that doesn't work in 2019b but will work in 2017a? Thanks.

**Comment by stefanengblom** [comment]
I don't think so. I am using 2021 now. PC is an issue though.

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shrike77101** [comment]
I'm on windows 
Processor	12th Gen Intel(R) Core(TM) i9-12900H   2.50 GHz
Installed RAM	32.0 GB (31.6 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by ahbarnett** [comment]
Probably Windows is the problem. I just pulled master and `make_all` works fine on ubuntu linux, R2022a.
Suggest you first get to know matlab. (there is no need for these accelerated routines until you first know matlab). Then check you can compile the simplest MEX examples:   https://www.mathworks.com/help/matlab/matlab_external/build-an-executable-mex-file.html
Etc.
Only then return to stenglib build. Good luck!

**Comment by shrike77101** [comment]
Very helpful, thank you!!
